### ISSUE TITLE
缺少材料时无法正常关机

### ISSUE THREAD

**Issue by crazyooooo-sk** [ljhljll/GTNH-NuclearCooler#1]
当开启多个反应堆时，若某个反应堆缺少材料（燃料棒或冷却单元）时关闭全局红石控制，程序无法正常退出。具体表现为程序会持续等待材料；其他反应堆的红石I/O端口的状态会保持不变，且不会继续监测核反应堆内物品状态。若在关闭全局红石控制信号时某个反应堆仍处于开启状态，会导致反应堆爆炸。

**Comment by ljhljll** [comment]
> 当开启多个反应堆时，若某个反应堆缺少材料且且关闭全局红石控制，程序无法正常退出。的状态会保持不变，不会继续监测核反应堆内状态项目。在关闭全局红石控制时某些反应堆仍处于开启状态，会导致反应堆爆炸。

是的，当缺少材料时会导致核电堆无法关闭，阻塞至对应反应堆填充材料后才会继续走关机流程，我正在重新设计流程防止这种阻塞情况，感谢反馈

**Comment by ljhljll** [comment]
> 当开启多个反应堆时，若某个反应堆缺少材料（燃料棒或冷却单元）时关闭全局红石控制，程序无法正常退出。的状态会保持不变，且不会继续监测核反应堆内状态项目。如果在关闭全局红石控制时某个反应堆仍处于开启状态，会导致反应堆爆炸。

是的，当缺少材料时会导致核电堆无法关闭，阻塞至对应反应堆填充材料后才会继续走关机流程，我正在重新设计流程防止这种阻塞情况，感谢反馈
