### ISSUE TITLE
coolantcellThread.lua中第9行报错

### ISSUE THREAD

**Issue by Strawxiguan** [ljhljll/GTNH-NuclearCooler#6]
![image](https://github.com/user-attachments/assets/255b301a-7b09-4a16-8501-3eb6d6c0b23c)
使用最新release版本的全部文件，按照B站视频制作四联核电，报错如下，核电仍可以运行，但发电为0EU/t
报错信息为latchRedstone值为nil

**Comment by ljhljll** [comment]
> ![图像](https://private-user-images.githubusercontent.com/127127787/375429625-255b301a-7b09-4a16-8501-3eb6d6c0b23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MDg3NzEsIm5iZiI6MTcyODYwODQ3MSwicGF0aCI6Ii8xMjcxMjc3ODcvMzc1NDI5NjI1LTI1NWIzMDFhLTdiMDktNGExNi04NTAxLTNlYjZkNmMwYjIzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwMTAxMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDNhMzk3NWJjNjhlMDc2MjQzNWJmNDQxOGViZmVkZDk4OTg0Y2Q3ZTU3NGY1MTQ5ODU5MzI4NjRmZTQ4MjhhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._5l_hRqiuD020R-73au-d7mEUYerjnalizwOpqB0ubw) 使用最新release版本的全部文件，按照B站视频制作四联核电，报错如下，核电仍可以运行，但发电为0EU/t 报错信息为latchRedstone设置为nil

可能是由于config.lua中你配置了错误的【energyLatchRedstone】参数从而导致oc在获取电量锁存器端口时无法获取，也有可能是OC线缆连接该端口时出现错误，请注意当你将OC的组件例如端口、转运器之类的东西敲掉后再放置下来，它对应的地址都会发生变化，需要在文件中进行更新

**Comment by ljhljll** [comment]
正常来说的话，如果不需要开启电量锁存器功能，应将其设置为energyLatchRedstone: -1，请检查你的配置文件，不开的话将其改为-1即可

**Comment by Strawxiguan** [comment]
> 正常来说的话，如果不需要开启电量锁存器功能，应将其设置为energyLatchRedstone: -1，请检查你的配置文件，不开的话将其改为-1即可

好的，目前我因为学习工作等原因没有在电脑前，我回去尝试一下，解决了我就把这个问题close了，十分感谢
